name: Destroy Tenant Infrastructure

on:
  workflow_dispatch:
    inputs:
      tenant_id:
        description: 'Unique User ID to destroy'
        required: true
        type: string

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: .
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: 'us-east-1'
    steps:
      - uses: actions/checkout@v4
      
      - uses: hashicorp/setup-terraform@v3

      - run: >
          terraform init
          -backend-config=bucket=multi-tenant-demo-03032026
          -backend-config=key=tenants/${{ github.event.inputs.tenant_id }}/terraform.tfstate
          -backend-config=region=us-east-1
          -backend-config=use_lockfile=true
          -reconfigure

      - run: terraform destroy -auto-approve